apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halo-memory
  namespace: halo-infra
spec:
  accessModes:
    - ReadWriteOnce  # NFS server pod is the only direct consumer
  storageClassName: vultr-block-storage-hdd-retain
  resources:
    requests:
      storage: 40Gi  # Vultr minimum
