import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import yaml

from .config import load_config
from .cron import CronJob, ValidationError
from halos.common.log import hlog


def cmd_add(args, cfg):
    tags = [t.strip() for t in args.tags.split(",")] if args.tags else []
    job_id = args.id if args.id else None

    try:
        job = CronJob.create(
            jobs_dir=cfg.jobs_dir,
            title=args.title,
            schedule=args.schedule,
            command=args.command,
            enabled=not args.disabled,
            tags=tags,
            job_id=job_id,
        )
    except ValidationError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    hlog("cronctl", "info", "job_created", {"id": job.id, "title": args.title})

    if args.json:
        print(json.dumps({"id": job.id, "file": str(job.file_path)}, indent=2))
    else:
        print(f"created  {job.id}  {job.file_path.name}")
    return 0


def cmd_list(args, cfg):
    jobs = _load_all_jobs(cfg.jobs_dir)

    if args.json:
        print(json.dumps([j.data for j in jobs], indent=2))
    else:
        if not jobs:
            print("no cron jobs defined")
            return 0
        fmt = "{:<30} {:<8} {:<20} {}"
        print(fmt.format("ID", "ENABLED", "SCHEDULE", "COMMAND"))
        print("-" * 90)
        for j in jobs:
            enabled = "yes" if j.enabled else "no"
            cmd = j.command[:40]
            print(fmt.format(j.id, enabled, j.schedule, cmd))
    return 0


def cmd_enable(args, cfg):
    job = _find_job(cfg.jobs_dir, args.id)
    if not job:
        print(f"ERROR: job '{args.id}' not found", file=sys.stderr)
        sys.exit(1)
    job.data["enabled"] = True
    job.save()
    hlog("cronctl", "info", "job_toggled", {"id": job.id, "enabled": True})
    print(f"enabled  {job.id}")
    return 0


def cmd_disable(args, cfg):
    job = _find_job(cfg.jobs_dir, args.id)
    if not job:
        print(f"ERROR: job '{args.id}' not found", file=sys.stderr)
        sys.exit(1)
    job.data["enabled"] = False
    job.save()
    hlog("cronctl", "info", "job_toggled", {"id": job.id, "enabled": False})
    print(f"disabled  {job.id}")
    return 0


def cmd_install(args, cfg):
    jobs = _load_all_jobs(cfg.jobs_dir)
    enabled = [j for j in jobs if j.enabled]

    project_root = str(cfg.base_dir)
    lines = [
        "# Generated by cronctl — do not edit manually",
        f"# {len(enabled)} enabled jobs of {len(jobs)} total",
        "",
    ]
    for j in enabled:
        lines.append(f"# {j.title}")
        lines.append(j.to_crontab_line(project_root))
        lines.append("")

    content = "\n".join(lines) + "\n"

    if args.json:
        print(json.dumps({"jobs": len(enabled), "file": str(cfg.output_file)}, indent=2))
    else:
        cfg.output_file.parent.mkdir(parents=True, exist_ok=True)
        tmp = str(cfg.output_file) + ".tmp"
        Path(tmp).write_text(content)
        os.replace(tmp, str(cfg.output_file))
        print(f"wrote {len(enabled)} jobs to {cfg.output_file}")

        if getattr(args, "execute", False) and cfg.install_method == "user-crontab":
            subprocess.run(["crontab", str(cfg.output_file)], check=True)
            print("installed to user crontab")
        elif getattr(args, "execute", False):
            print("install_method=file — crontab written but not installed to system")
    return 0


def cmd_uninstall(args, cfg):
    if cfg.output_file.exists():
        cfg.output_file.unlink()
        print(f"removed {cfg.output_file}")
    else:
        print("no generated crontab found")
    return 0


def cmd_status(args, cfg):
    jobs = _load_all_jobs(cfg.jobs_dir)
    enabled = [j for j in jobs if j.enabled]
    disabled = [j for j in jobs if not j.enabled]

    installed = cfg.output_file.exists()

    if args.json:
        print(json.dumps({
            "total": len(jobs),
            "enabled": len(enabled),
            "disabled": len(disabled),
            "crontab_file": str(cfg.output_file),
            "installed": installed,
        }, indent=2))
    else:
        print(f"Jobs defined:  {len(jobs)}")
        print(f"  enabled:     {len(enabled)}")
        print(f"  disabled:    {len(disabled)}")
        print(f"Crontab file:  {cfg.output_file}")
        print(f"  installed:   {'yes' if installed else 'no'}")
        print()
        if enabled:
            print("Enabled jobs:")
            for j in enabled:
                print(f"  {j.id:<30} {j.schedule}")
        if disabled:
            print("Disabled jobs:")
            for j in disabled:
                print(f"  {j.id:<30} {j.schedule}")
    return 0


def cmd_run(args, cfg):
    job = _find_job(cfg.jobs_dir, args.id)
    if not job:
        print(f"ERROR: job '{args.id}' not found", file=sys.stderr)
        sys.exit(1)

    if args.dry_run:
        print(f"DRY-RUN  {job.id}  {job.command}")
        return 0

    print(f"running  {job.id}  {job.command}")
    result = subprocess.run(
        job.command, shell=True, cwd=str(cfg.base_dir),
        capture_output=True, text=True,
    )
    if result.stdout:
        print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode != 0:
        print(f"exit code: {result.returncode}", file=sys.stderr)
        sys.exit(result.returncode)
    return 0


def _load_all_jobs(jobs_dir: Path) -> list[CronJob]:
    if not jobs_dir.exists():
        return []
    jobs = []
    for f in sorted(jobs_dir.glob("*.yaml")):
        try:
            jobs.append(CronJob.from_file(f))
        except (ValueError, yaml.YAMLError, OSError) as e:
            print(f"WARN: skipping {f.name}: {e}", file=sys.stderr)
    return jobs


def _find_job(jobs_dir: Path, job_id: str) -> CronJob | None:
    for j in _load_all_jobs(jobs_dir):
        if j.id == job_id:
            return j
    return None


def build_parser():
    parser = argparse.ArgumentParser(
        prog="cronctl",
        description="halos cron job management CLI",
    )
    parser.add_argument("--config", default=None, help="Path to cronctl.yaml")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--dry-run", action="store_true", dest="dry_run")
    parser.add_argument("--verbose", action="store_true")

    sub = parser.add_subparsers(dest="subcommand")

    # add
    add = sub.add_parser("add", help="Create a new cron job definition")
    add.add_argument("--title", required=True)
    add.add_argument("--schedule", required=True, help="Cron expression (5 fields)")
    add.add_argument("--command", required=True)
    add.add_argument("--id", default=None, help="Job ID (default: slugified title)")
    add.add_argument("--tags", default=None)
    add.add_argument("--disabled", action="store_true")

    # list
    sub.add_parser("list", help="List all defined cron jobs")

    # enable
    en = sub.add_parser("enable", help="Enable a cron job")
    en.add_argument("id")

    # disable
    dis = sub.add_parser("disable", help="Disable a cron job")
    dis.add_argument("id")

    # install
    inst = sub.add_parser("install", help="Generate crontab from enabled jobs")
    inst.add_argument("--execute", action="store_true",
                      help="Install to system crontab (requires install_method=user-crontab)")

    # uninstall
    sub.add_parser("uninstall", help="Remove the generated crontab")

    # status
    sub.add_parser("status", help="Show job and installation status")

    # run
    run = sub.add_parser("run", help="Manually trigger a job")
    run.add_argument("id")

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    if not args.subcommand:
        parser.print_help()
        sys.exit(0)

    try:
        cfg = load_config(args.config)
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(4)

    dispatch = {
        "add": cmd_add,
        "list": cmd_list,
        "enable": cmd_enable,
        "disable": cmd_disable,
        "install": cmd_install,
        "uninstall": cmd_uninstall,
        "status": cmd_status,
        "run": cmd_run,
    }

    if args.subcommand in dispatch:
        sys.exit(dispatch[args.subcommand](args, cfg) or 0)
    else:
        parser.print_help()
        sys.exit(0)
