apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: halo-data
  namespace: halo-aura
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
